# Problem: Optimizing Warehouse Robot Movement
A warehouse robot needs to pick up an item from a shelf and deliver it to a packing area. The environment is represented as a grid, and the robot must navigate from a starting position to a target position while avoiding penalties for moving inefficiently.

In [2]:
import numpy as np

# Environment: 5x5 grid
grid_size = 5
states = grid_size * grid_size  # Total states
actions = 4  # Actions: 0=Up, 1=Right, 2=Down, 3=Left
rewards = -1 * np.ones((grid_size, grid_size))  # Default penalty for every move
rewards[4, 4] = 100  # Reward for reaching the target (bottom-right corner)
target_state = (4, 4)

# Transition logic
def next_position(state, action):
    row, col = divmod(state, grid_size)
    if action == 0 and row > 0:  # Move up
        row -= 1
    elif action == 1 and col < grid_size - 1:  # Move right
        col += 1
    elif action == 2 and row < grid_size - 1:  # Move down
        row += 1
    elif action == 3 and col > 0:  # Move left
        col -= 1
    return row * grid_size + col

# Q-learning Parameters
q_table = np.zeros((states, actions))
alpha = 0.1  # Learning rate
gamma = 0.9  # Discount factor
epsilon = 1.0  # Exploration rate
epsilon_decay = 0.995
episodes = 5000

# Q-Learning
for _ in range(episodes):
    state = 0  # Start at top-left corner
    done = False
    while not done:
        # Choose action (epsilon-greedy)
        if np.random.rand() < epsilon:
            action = np.random.choice(actions)
        else:
            action = np.argmax(q_table[state])

        next_state = next_position(state, action)
        reward = rewards[divmod(next_state, grid_size)]
        done = next_state == target_state[0] * grid_size + target_state[1]

        # Update Q-value
        best_next_action = np.max(q_table[next_state])
        q_table[state, action] += alpha * (reward + gamma * best_next_action - q_table[state, action])
        state = next_state

    # Decay epsilon
    epsilon = max(epsilon * epsilon_decay, 0.1)

# Display the trained Q-table
print("Trained Q-table:")
print(q_table)


Trained Q-table:
[[ 37.35138612  42.612659    42.6126509   37.35138933]
 [ 42.61265384  37.35133842  48.45851     37.35134595]
 [ 13.20081665  14.34315964  28.84396433  42.61265426]
 [  2.44971686   3.53271563  35.17172844   2.52068919]
 [  3.76636155   4.64220823  18.09355348   0.11582807]
 [ 29.86279916  48.45851     36.34083768  34.14111746]
 [ 42.61265827  54.95388681  54.9539      42.61264457]
 [ 18.3047395   34.12132903  62.17099955  34.63146455]
 [  5.0631692   11.9304682   61.8646587   18.70860796]
 [  3.64825356  11.92908537  40.8414766    7.78265956]
 [ 14.64890403  54.95388898  40.66176262  22.4212957 ]
 [ 48.45850963  62.17099729  62.171       48.4583122 ]
 [ 50.59803921  63.04886043  70.19        47.87634376]
 [ 20.12945934  48.44723634  78.33607169  42.17275512]
 [ 14.34537934  38.56387777  76.73118132  27.18158006]
 [ 19.11061782  62.17098883  36.62865837  32.09131997]
 [ 54.95388814  70.18999397  70.19        54.95366625]
 [ 58.42769924  77.5773694   79.1         61.319

## Metrics

- **Convergence:** Check if the robot learns to reach the target.
- **Path Efficiency:** Calculate the total number of steps taken.
- **Reward Accumulation:** Ensure the robot maximizes cumulative rewards.